Ensure all occurrences are replaced in path parameter sanitization
cyclosproject/ng-openapi-gen pull request #229
Opened 2022-07-13 23:22 UTC by danmcgee-soda

Javascript replace only acts on the first found match if the pattern is
a string. Change the patterns to regular expressions and use the global
flag to ensure all occurrences are replaced.

This also updates the test to include some checks around the three
special characters we un-escape in this code.

We noticed this with CodeQL Security Scanning on our repository- this rule was tripped: https://github.com/github/codeql/blob/56786790fcf88b79d1d26b946ff36dfe2d6f33ac/javascript/ql/src/Security/CWE-116/IncompleteSanitization.ql

2022-07-22 06:06 UTC, mojoaxel requested changes
LGTM

2022-07-22 06:06 UTC, mojoaxel approved these changes

2022-08-08 16:52 UTC, danmcgee-soda commented
@mojoaxel do you know what I need to do to get this merged?

@luisfpg is there anything additional I can do to help here?

2022-08-09 11:40 UTC, luisfpg commented
> @luisfpg is there anything additional I can do to help here?

I'm sorry, I'm having troubles lately to find some time for this project.
From Cyclos itself, the project covers 100% of the needs already for years, so I'm doing all the maintainance in my free time.
I'll do my best for merge some PRs in the next few days.

2022-08-25 12:23 UTC, merged